version: '3.8'

services:
  # Development - Translation Service
  translation-service:
    build: ../translation-service
    container_name: creole-translation-dev
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=debug
      - RELOAD=true
    volumes:
      - ../translation-service:/app
    depends_on:
      - redis
    networks:
      - creole-network
    restart: unless-stopped

  # Development - Speech-to-Text Service
  stt-service:
    build: ../speech-to-text-service
    container_name: creole-stt-dev
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=debug
      - RELOAD=true
    volumes:
      - ../speech-to-text-service:/app
    depends_on:
      - redis
    networks:
      - creole-network
    restart: unless-stopped

  # Development - Text-to-Speech Service
  tts-service:
    build: ../text-to-speech-service
    container_name: creole-tts-dev
    ports:
      - "8003:8003"
    environment:
      - PORT=8003
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=debug
      - RELOAD=true
    volumes:
      - ../text-to-speech-service:/app
    depends_on:
      - redis
    networks:
      - creole-network
    restart: unless-stopped

  # Development - Web Application
  web-app:
    build: ../creole-translator-web
    container_name: creole-web-dev
    ports:
      - "3000:3000"
    environment:
      - VITE_TRANSLATION_API_URL=http://localhost:8001
      - VITE_STT_API_URL=http://localhost:8002
      - VITE_TTS_API_URL=http://localhost:8003
      - NODE_ENV=development
    volumes:
      - ../creole-translator-web:/app
      - /app/node_modules
    depends_on:
      - translation-service
      - stt-service
      - tts-service
    networks:
      - creole-network
    restart: unless-stopped

  # Redis for development
  redis:
    image: redis:7-alpine
    container_name: creole-redis-dev
    ports:
      - "6379:6379"
    networks:
      - creole-network
    restart: unless-stopped

networks:
  creole-network:
    driver: bridge